config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "products/index"
  root "products#index"

  resources :products

  get "/products", to: "products#index"

get "/products/new", to: "products#new"
post "/products", to: "products#create"

get "/products/:id", to: "products#show"

get "/products/:id/edit", to: "products#edit"
patch "/products/:id", to: "products#update"
put "/products/:id", to: "products#update"

delete "/products/:id", to: "products#destroy"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :featured_image
    has_rich_text :description
    validates :inventory_count, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.expect(product: [ :name, :description, :featured_image, :inventory_count ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Newstore" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="menu">
        <div class="header-nav__withSearch">
        <input type="text" placeholder="Bạn muốn tìm gì?">
      </div>

    <% if !user_signed_in? %>
      <p class="sign_in"><%= link_to "Đăng Nhập", new_user_session_path %></p>
    <% end %>
    <% if user_signed_in? %>
      <%= button_to "Đăng xuất", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= link_to "Trang Chủ", root_path %>
  </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>

</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.label :featured_image %>
    <%= form.file_field :featured_image, accept: "image/*" %>
  </div>

<div>
    <%= form.label :inventory_count, style: "display: block" %>
    <%= form.number_field :inventory_count %>
  </div>
  <div>
    <%= form.submit "Save Product", class: "submit-button" %>
  </div>
<% end %>

app/views/products/_inventory.html.erb
<% if product.inventory_count? %>
  <p><%= product.inventory_count %> in stock</p>
<% else %>
  <p>Out of stock</p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form", product: @product %>
<%= link_to "Cancel", @product, class: "cancel-link" %>

app/views/products/index.html.erb
<h1>Products</h1>
    <% if user_signed_in? %>
<%= link_to "New product", new_product_path, class: "new-product" %>
<% end %>
<div id="products">
  <% @products.each do |product| %>
    <div>
      <%= link_to product.name, product %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>
<%= link_to "Cancel", products_path, class: "cancel-link" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= render "inventory", product: @product %>

<p class="product-description"><%= @product.description %></p>

<% if @product.featured_image.attached? %>
  <%= image_tag @product.featured_image, class: "product-image" %>
<% end %>

<div class="action-buttons">
  <%= link_to "Back", products_path, class: "back-link" %>
  <%= link_to "Edit", edit_product_path(@product), class: "edit-link" %>
  <%= button_to "Delete", @product, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "delete-button" %>
</div>